Init cppcheck part
Judge-Girl/Code-Quality-Inspection pull request #6
Opened 2020-11-25 18:46 UTC by edisonhello

#3 
* Not sure if environment broke
* Not sure if python files' location correct
* Add simple testcase
* Add simple test

2020-11-27 15:26 UTC, Johnny850807 requested changes
Review done...Thanks!

2020-11-27 15:26 UTC, Johnny850807 commented on src/main/python/codingStyleAnalyzer/main.py
> +    main()
rename the folder `codeStyleAnalyzer` to `code_style`

2020-11-27 15:26 UTC, Johnny850807 commented on src/main/python/codingStyleAnalyzer/coding_style_analyzer.py
> +    dump_content = ''.join(open(dump_file_path, "r").readlines())
```python
with open(dump_file_path, "r") as f:
    dump_content = ''.join(f.readlines())
```

2020-11-27 15:26 UTC, Johnny850807 commented on src/main/python/codingStyleAnalyzer/coding_style_analyzer.py
> +    xml = XML.fromstring(get_dump_result(path))
Rename this module `coding_style_analyzer.py` to `cpp_check.py` since you are just invoking the cppcheck tool in this file.

2020-11-27 15:26 UTC, Johnny850807 commented on src/main/python/codingStyleAnalyzer/coding_style_analyzer.py
> +    return None
Why is this returning `None `? If this is incomplete, mark it with a TODO comment.
```python
# TODO ${description}
```

2020-11-27 15:26 UTC, Johnny850807 commented on src/main/python/codingStyleAnalyzer/coding_style_analyzer.py
> +def get_dump_result(path):
rename to `dump_cpp_check_result(file_path)`

BTW, Does cppcheck only copes with a file?

2020-11-27 15:26 UTC, Johnny850807 commented on src/main/python/codingStyleAnalyzer/main.py
> +    print(XML.tostring(xml).decode())
could you include the example result in the PR's description?

as I couldn't imagine what the output xml will be meanwhile

2020-11-28 20:19 UTC, edisonhello commented
Cppcheck supports recursively check. However, it will generate `.dump` file for each files it parse, so we still needs to make traversal into folders to read those parse files.

2020-11-30 06:55 UTC, Johnny850807 approved these changes
LGTM

2020-11-30 09:14 UTC, merged